# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.20.1-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.20.1-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xd/Research/psdr-cuda

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xd/Research/psdr-cuda

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.20.1-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.20.1-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xd/Research/psdr-cuda/CMakeFiles /home/xd/Research/psdr-cuda//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xd/Research/psdr-cuda/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named psdr_cuda

# Build rule for target.
psdr_cuda: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 psdr_cuda
.PHONY : psdr_cuda

# fast build rule for target.
psdr_cuda/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/build
.PHONY : psdr_cuda/fast

#=============================================================================
# Target rules for targets named ptx

# Build rule for target.
ptx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ptx
.PHONY : ptx

# fast build rule for target.
ptx/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ptx.dir/build.make CMakeFiles/ptx.dir/build
.PHONY : ptx/fast

cuda/psdr_cuda.o: cuda/psdr_cuda.cpp.o
.PHONY : cuda/psdr_cuda.o

# target to build an object file
cuda/psdr_cuda.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ptx.dir/build.make CMakeFiles/ptx.dir/cuda/psdr_cuda.cpp.o
.PHONY : cuda/psdr_cuda.cpp.o

cuda/psdr_cuda.i: cuda/psdr_cuda.cpp.i
.PHONY : cuda/psdr_cuda.i

# target to preprocess a source file
cuda/psdr_cuda.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ptx.dir/build.make CMakeFiles/ptx.dir/cuda/psdr_cuda.cpp.i
.PHONY : cuda/psdr_cuda.cpp.i

cuda/psdr_cuda.s: cuda/psdr_cuda.cpp.s
.PHONY : cuda/psdr_cuda.s

# target to generate assembly for a file
cuda/psdr_cuda.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ptx.dir/build.make CMakeFiles/ptx.dir/cuda/psdr_cuda.cpp.s
.PHONY : cuda/psdr_cuda.cpp.s

src/bsdf/diffuse.o: src/bsdf/diffuse.cpp.o
.PHONY : src/bsdf/diffuse.o

# target to build an object file
src/bsdf/diffuse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/bsdf/diffuse.cpp.o
.PHONY : src/bsdf/diffuse.cpp.o

src/bsdf/diffuse.i: src/bsdf/diffuse.cpp.i
.PHONY : src/bsdf/diffuse.i

# target to preprocess a source file
src/bsdf/diffuse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/bsdf/diffuse.cpp.i
.PHONY : src/bsdf/diffuse.cpp.i

src/bsdf/diffuse.s: src/bsdf/diffuse.cpp.s
.PHONY : src/bsdf/diffuse.s

# target to generate assembly for a file
src/bsdf/diffuse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/bsdf/diffuse.cpp.s
.PHONY : src/bsdf/diffuse.cpp.s

src/bsdf/ggx.o: src/bsdf/ggx.cpp.o
.PHONY : src/bsdf/ggx.o

# target to build an object file
src/bsdf/ggx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/bsdf/ggx.cpp.o
.PHONY : src/bsdf/ggx.cpp.o

src/bsdf/ggx.i: src/bsdf/ggx.cpp.i
.PHONY : src/bsdf/ggx.i

# target to preprocess a source file
src/bsdf/ggx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/bsdf/ggx.cpp.i
.PHONY : src/bsdf/ggx.cpp.i

src/bsdf/ggx.s: src/bsdf/ggx.cpp.s
.PHONY : src/bsdf/ggx.s

# target to generate assembly for a file
src/bsdf/ggx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/bsdf/ggx.cpp.s
.PHONY : src/bsdf/ggx.cpp.s

src/bsdf/roughconductor.o: src/bsdf/roughconductor.cpp.o
.PHONY : src/bsdf/roughconductor.o

# target to build an object file
src/bsdf/roughconductor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/bsdf/roughconductor.cpp.o
.PHONY : src/bsdf/roughconductor.cpp.o

src/bsdf/roughconductor.i: src/bsdf/roughconductor.cpp.i
.PHONY : src/bsdf/roughconductor.i

# target to preprocess a source file
src/bsdf/roughconductor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/bsdf/roughconductor.cpp.i
.PHONY : src/bsdf/roughconductor.cpp.i

src/bsdf/roughconductor.s: src/bsdf/roughconductor.cpp.s
.PHONY : src/bsdf/roughconductor.s

# target to generate assembly for a file
src/bsdf/roughconductor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/bsdf/roughconductor.cpp.s
.PHONY : src/bsdf/roughconductor.cpp.s

src/bsdf/subsurface.o: src/bsdf/subsurface.cpp.o
.PHONY : src/bsdf/subsurface.o

# target to build an object file
src/bsdf/subsurface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/bsdf/subsurface.cpp.o
.PHONY : src/bsdf/subsurface.cpp.o

src/bsdf/subsurface.i: src/bsdf/subsurface.cpp.i
.PHONY : src/bsdf/subsurface.i

# target to preprocess a source file
src/bsdf/subsurface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/bsdf/subsurface.cpp.i
.PHONY : src/bsdf/subsurface.cpp.i

src/bsdf/subsurface.s: src/bsdf/subsurface.cpp.s
.PHONY : src/bsdf/subsurface.s

# target to generate assembly for a file
src/bsdf/subsurface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/bsdf/subsurface.cpp.s
.PHONY : src/bsdf/subsurface.cpp.s

src/core/bitmap.o: src/core/bitmap.cpp.o
.PHONY : src/core/bitmap.o

# target to build an object file
src/core/bitmap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/bitmap.cpp.o
.PHONY : src/core/bitmap.cpp.o

src/core/bitmap.i: src/core/bitmap.cpp.i
.PHONY : src/core/bitmap.i

# target to preprocess a source file
src/core/bitmap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/bitmap.cpp.i
.PHONY : src/core/bitmap.cpp.i

src/core/bitmap.s: src/core/bitmap.cpp.s
.PHONY : src/core/bitmap.s

# target to generate assembly for a file
src/core/bitmap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/bitmap.cpp.s
.PHONY : src/core/bitmap.cpp.s

src/core/bitmap_loader.o: src/core/bitmap_loader.cpp.o
.PHONY : src/core/bitmap_loader.o

# target to build an object file
src/core/bitmap_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/bitmap_loader.cpp.o
.PHONY : src/core/bitmap_loader.cpp.o

src/core/bitmap_loader.i: src/core/bitmap_loader.cpp.i
.PHONY : src/core/bitmap_loader.i

# target to preprocess a source file
src/core/bitmap_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/bitmap_loader.cpp.i
.PHONY : src/core/bitmap_loader.cpp.i

src/core/bitmap_loader.s: src/core/bitmap_loader.cpp.s
.PHONY : src/core/bitmap_loader.s

# target to generate assembly for a file
src/core/bitmap_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/bitmap_loader.cpp.s
.PHONY : src/core/bitmap_loader.cpp.s

src/core/cube_distrb.o: src/core/cube_distrb.cpp.o
.PHONY : src/core/cube_distrb.o

# target to build an object file
src/core/cube_distrb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/cube_distrb.cpp.o
.PHONY : src/core/cube_distrb.cpp.o

src/core/cube_distrb.i: src/core/cube_distrb.cpp.i
.PHONY : src/core/cube_distrb.i

# target to preprocess a source file
src/core/cube_distrb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/cube_distrb.cpp.i
.PHONY : src/core/cube_distrb.cpp.i

src/core/cube_distrb.s: src/core/cube_distrb.cpp.s
.PHONY : src/core/cube_distrb.s

# target to generate assembly for a file
src/core/cube_distrb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/cube_distrb.cpp.s
.PHONY : src/core/cube_distrb.cpp.s

src/core/pmf.o: src/core/pmf.cpp.o
.PHONY : src/core/pmf.o

# target to build an object file
src/core/pmf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/pmf.cpp.o
.PHONY : src/core/pmf.cpp.o

src/core/pmf.i: src/core/pmf.cpp.i
.PHONY : src/core/pmf.i

# target to preprocess a source file
src/core/pmf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/pmf.cpp.i
.PHONY : src/core/pmf.cpp.i

src/core/pmf.s: src/core/pmf.cpp.s
.PHONY : src/core/pmf.s

# target to generate assembly for a file
src/core/pmf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/pmf.cpp.s
.PHONY : src/core/pmf.cpp.s

src/core/sampler.o: src/core/sampler.cpp.o
.PHONY : src/core/sampler.o

# target to build an object file
src/core/sampler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/sampler.cpp.o
.PHONY : src/core/sampler.cpp.o

src/core/sampler.i: src/core/sampler.cpp.i
.PHONY : src/core/sampler.i

# target to preprocess a source file
src/core/sampler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/sampler.cpp.i
.PHONY : src/core/sampler.cpp.i

src/core/sampler.s: src/core/sampler.cpp.s
.PHONY : src/core/sampler.s

# target to generate assembly for a file
src/core/sampler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/core/sampler.cpp.s
.PHONY : src/core/sampler.cpp.s

src/emitter/area.o: src/emitter/area.cpp.o
.PHONY : src/emitter/area.o

# target to build an object file
src/emitter/area.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/emitter/area.cpp.o
.PHONY : src/emitter/area.cpp.o

src/emitter/area.i: src/emitter/area.cpp.i
.PHONY : src/emitter/area.i

# target to preprocess a source file
src/emitter/area.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/emitter/area.cpp.i
.PHONY : src/emitter/area.cpp.i

src/emitter/area.s: src/emitter/area.cpp.s
.PHONY : src/emitter/area.s

# target to generate assembly for a file
src/emitter/area.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/emitter/area.cpp.s
.PHONY : src/emitter/area.cpp.s

src/emitter/envmap.o: src/emitter/envmap.cpp.o
.PHONY : src/emitter/envmap.o

# target to build an object file
src/emitter/envmap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/emitter/envmap.cpp.o
.PHONY : src/emitter/envmap.cpp.o

src/emitter/envmap.i: src/emitter/envmap.cpp.i
.PHONY : src/emitter/envmap.i

# target to preprocess a source file
src/emitter/envmap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/emitter/envmap.cpp.i
.PHONY : src/emitter/envmap.cpp.i

src/emitter/envmap.s: src/emitter/envmap.cpp.s
.PHONY : src/emitter/envmap.s

# target to generate assembly for a file
src/emitter/envmap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/emitter/envmap.cpp.s
.PHONY : src/emitter/envmap.cpp.s

src/integrator/direct.o: src/integrator/direct.cpp.o
.PHONY : src/integrator/direct.o

# target to build an object file
src/integrator/direct.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/direct.cpp.o
.PHONY : src/integrator/direct.cpp.o

src/integrator/direct.i: src/integrator/direct.cpp.i
.PHONY : src/integrator/direct.i

# target to preprocess a source file
src/integrator/direct.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/direct.cpp.i
.PHONY : src/integrator/direct.cpp.i

src/integrator/direct.s: src/integrator/direct.cpp.s
.PHONY : src/integrator/direct.s

# target to generate assembly for a file
src/integrator/direct.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/direct.cpp.s
.PHONY : src/integrator/direct.cpp.s

src/integrator/direct_origin.o: src/integrator/direct_origin.cpp.o
.PHONY : src/integrator/direct_origin.o

# target to build an object file
src/integrator/direct_origin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/direct_origin.cpp.o
.PHONY : src/integrator/direct_origin.cpp.o

src/integrator/direct_origin.i: src/integrator/direct_origin.cpp.i
.PHONY : src/integrator/direct_origin.i

# target to preprocess a source file
src/integrator/direct_origin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/direct_origin.cpp.i
.PHONY : src/integrator/direct_origin.cpp.i

src/integrator/direct_origin.s: src/integrator/direct_origin.cpp.s
.PHONY : src/integrator/direct_origin.s

# target to generate assembly for a file
src/integrator/direct_origin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/direct_origin.cpp.s
.PHONY : src/integrator/direct_origin.cpp.s

src/integrator/field.o: src/integrator/field.cpp.o
.PHONY : src/integrator/field.o

# target to build an object file
src/integrator/field.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/field.cpp.o
.PHONY : src/integrator/field.cpp.o

src/integrator/field.i: src/integrator/field.cpp.i
.PHONY : src/integrator/field.i

# target to preprocess a source file
src/integrator/field.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/field.cpp.i
.PHONY : src/integrator/field.cpp.i

src/integrator/field.s: src/integrator/field.cpp.s
.PHONY : src/integrator/field.s

# target to generate assembly for a file
src/integrator/field.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/field.cpp.s
.PHONY : src/integrator/field.cpp.s

src/integrator/integrator.o: src/integrator/integrator.cpp.o
.PHONY : src/integrator/integrator.o

# target to build an object file
src/integrator/integrator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/integrator.cpp.o
.PHONY : src/integrator/integrator.cpp.o

src/integrator/integrator.i: src/integrator/integrator.cpp.i
.PHONY : src/integrator/integrator.i

# target to preprocess a source file
src/integrator/integrator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/integrator.cpp.i
.PHONY : src/integrator/integrator.cpp.i

src/integrator/integrator.s: src/integrator/integrator.cpp.s
.PHONY : src/integrator/integrator.s

# target to generate assembly for a file
src/integrator/integrator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/integrator.cpp.s
.PHONY : src/integrator/integrator.cpp.s

src/integrator/laser.o: src/integrator/laser.cpp.o
.PHONY : src/integrator/laser.o

# target to build an object file
src/integrator/laser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/laser.cpp.o
.PHONY : src/integrator/laser.cpp.o

src/integrator/laser.i: src/integrator/laser.cpp.i
.PHONY : src/integrator/laser.i

# target to preprocess a source file
src/integrator/laser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/laser.cpp.i
.PHONY : src/integrator/laser.cpp.i

src/integrator/laser.s: src/integrator/laser.cpp.s
.PHONY : src/integrator/laser.s

# target to generate assembly for a file
src/integrator/laser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/integrator/laser.cpp.s
.PHONY : src/integrator/laser.cpp.s

src/optix/ptx.o: src/optix/ptx.cpp.o
.PHONY : src/optix/ptx.o

# target to build an object file
src/optix/ptx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/optix/ptx.cpp.o
.PHONY : src/optix/ptx.cpp.o

src/optix/ptx.i: src/optix/ptx.cpp.i
.PHONY : src/optix/ptx.i

# target to preprocess a source file
src/optix/ptx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/optix/ptx.cpp.i
.PHONY : src/optix/ptx.cpp.i

src/optix/ptx.s: src/optix/ptx.cpp.s
.PHONY : src/optix/ptx.s

# target to generate assembly for a file
src/optix/ptx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/optix/ptx.cpp.s
.PHONY : src/optix/ptx.cpp.s

src/psdr.o: src/psdr.cpp.o
.PHONY : src/psdr.o

# target to build an object file
src/psdr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/psdr.cpp.o
.PHONY : src/psdr.cpp.o

src/psdr.i: src/psdr.cpp.i
.PHONY : src/psdr.i

# target to preprocess a source file
src/psdr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/psdr.cpp.i
.PHONY : src/psdr.cpp.i

src/psdr.s: src/psdr.cpp.s
.PHONY : src/psdr.s

# target to generate assembly for a file
src/psdr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/psdr.cpp.s
.PHONY : src/psdr.cpp.s

src/scene/scene.o: src/scene/scene.cpp.o
.PHONY : src/scene/scene.o

# target to build an object file
src/scene/scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/scene/scene.cpp.o
.PHONY : src/scene/scene.cpp.o

src/scene/scene.i: src/scene/scene.cpp.i
.PHONY : src/scene/scene.i

# target to preprocess a source file
src/scene/scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/scene/scene.cpp.i
.PHONY : src/scene/scene.cpp.i

src/scene/scene.s: src/scene/scene.cpp.s
.PHONY : src/scene/scene.s

# target to generate assembly for a file
src/scene/scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/scene/scene.cpp.s
.PHONY : src/scene/scene.cpp.s

src/scene/scene_loader.o: src/scene/scene_loader.cpp.o
.PHONY : src/scene/scene_loader.o

# target to build an object file
src/scene/scene_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/scene/scene_loader.cpp.o
.PHONY : src/scene/scene_loader.cpp.o

src/scene/scene_loader.i: src/scene/scene_loader.cpp.i
.PHONY : src/scene/scene_loader.i

# target to preprocess a source file
src/scene/scene_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/scene/scene_loader.cpp.i
.PHONY : src/scene/scene_loader.cpp.i

src/scene/scene_loader.s: src/scene/scene_loader.cpp.s
.PHONY : src/scene/scene_loader.s

# target to generate assembly for a file
src/scene/scene_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/scene/scene_loader.cpp.s
.PHONY : src/scene/scene_loader.cpp.s

src/scene/scene_optix.o: src/scene/scene_optix.cpp.o
.PHONY : src/scene/scene_optix.o

# target to build an object file
src/scene/scene_optix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/scene/scene_optix.cpp.o
.PHONY : src/scene/scene_optix.cpp.o

src/scene/scene_optix.i: src/scene/scene_optix.cpp.i
.PHONY : src/scene/scene_optix.i

# target to preprocess a source file
src/scene/scene_optix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/scene/scene_optix.cpp.i
.PHONY : src/scene/scene_optix.cpp.i

src/scene/scene_optix.s: src/scene/scene_optix.cpp.s
.PHONY : src/scene/scene_optix.s

# target to generate assembly for a file
src/scene/scene_optix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/scene/scene_optix.cpp.s
.PHONY : src/scene/scene_optix.cpp.s

src/sensor/perspective.o: src/sensor/perspective.cpp.o
.PHONY : src/sensor/perspective.o

# target to build an object file
src/sensor/perspective.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/sensor/perspective.cpp.o
.PHONY : src/sensor/perspective.cpp.o

src/sensor/perspective.i: src/sensor/perspective.cpp.i
.PHONY : src/sensor/perspective.i

# target to preprocess a source file
src/sensor/perspective.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/sensor/perspective.cpp.i
.PHONY : src/sensor/perspective.cpp.i

src/sensor/perspective.s: src/sensor/perspective.cpp.s
.PHONY : src/sensor/perspective.s

# target to generate assembly for a file
src/sensor/perspective.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/sensor/perspective.cpp.s
.PHONY : src/sensor/perspective.cpp.s

src/sensor/sensor.o: src/sensor/sensor.cpp.o
.PHONY : src/sensor/sensor.o

# target to build an object file
src/sensor/sensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/sensor/sensor.cpp.o
.PHONY : src/sensor/sensor.cpp.o

src/sensor/sensor.i: src/sensor/sensor.cpp.i
.PHONY : src/sensor/sensor.i

# target to preprocess a source file
src/sensor/sensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/sensor/sensor.cpp.i
.PHONY : src/sensor/sensor.cpp.i

src/sensor/sensor.s: src/sensor/sensor.cpp.s
.PHONY : src/sensor/sensor.s

# target to generate assembly for a file
src/sensor/sensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/sensor/sensor.cpp.s
.PHONY : src/sensor/sensor.cpp.s

src/shape/mesh.o: src/shape/mesh.cpp.o
.PHONY : src/shape/mesh.o

# target to build an object file
src/shape/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/shape/mesh.cpp.o
.PHONY : src/shape/mesh.cpp.o

src/shape/mesh.i: src/shape/mesh.cpp.i
.PHONY : src/shape/mesh.i

# target to preprocess a source file
src/shape/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/shape/mesh.cpp.i
.PHONY : src/shape/mesh.cpp.i

src/shape/mesh.s: src/shape/mesh.cpp.s
.PHONY : src/shape/mesh.s

# target to generate assembly for a file
src/shape/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/psdr_cuda.dir/build.make CMakeFiles/psdr_cuda.dir/src/shape/mesh.cpp.s
.PHONY : src/shape/mesh.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... psdr_cuda"
	@echo "... ptx"
	@echo "... cuda/psdr_cuda.o"
	@echo "... cuda/psdr_cuda.i"
	@echo "... cuda/psdr_cuda.s"
	@echo "... src/bsdf/diffuse.o"
	@echo "... src/bsdf/diffuse.i"
	@echo "... src/bsdf/diffuse.s"
	@echo "... src/bsdf/ggx.o"
	@echo "... src/bsdf/ggx.i"
	@echo "... src/bsdf/ggx.s"
	@echo "... src/bsdf/roughconductor.o"
	@echo "... src/bsdf/roughconductor.i"
	@echo "... src/bsdf/roughconductor.s"
	@echo "... src/bsdf/subsurface.o"
	@echo "... src/bsdf/subsurface.i"
	@echo "... src/bsdf/subsurface.s"
	@echo "... src/core/bitmap.o"
	@echo "... src/core/bitmap.i"
	@echo "... src/core/bitmap.s"
	@echo "... src/core/bitmap_loader.o"
	@echo "... src/core/bitmap_loader.i"
	@echo "... src/core/bitmap_loader.s"
	@echo "... src/core/cube_distrb.o"
	@echo "... src/core/cube_distrb.i"
	@echo "... src/core/cube_distrb.s"
	@echo "... src/core/pmf.o"
	@echo "... src/core/pmf.i"
	@echo "... src/core/pmf.s"
	@echo "... src/core/sampler.o"
	@echo "... src/core/sampler.i"
	@echo "... src/core/sampler.s"
	@echo "... src/emitter/area.o"
	@echo "... src/emitter/area.i"
	@echo "... src/emitter/area.s"
	@echo "... src/emitter/envmap.o"
	@echo "... src/emitter/envmap.i"
	@echo "... src/emitter/envmap.s"
	@echo "... src/integrator/direct.o"
	@echo "... src/integrator/direct.i"
	@echo "... src/integrator/direct.s"
	@echo "... src/integrator/direct_origin.o"
	@echo "... src/integrator/direct_origin.i"
	@echo "... src/integrator/direct_origin.s"
	@echo "... src/integrator/field.o"
	@echo "... src/integrator/field.i"
	@echo "... src/integrator/field.s"
	@echo "... src/integrator/integrator.o"
	@echo "... src/integrator/integrator.i"
	@echo "... src/integrator/integrator.s"
	@echo "... src/integrator/laser.o"
	@echo "... src/integrator/laser.i"
	@echo "... src/integrator/laser.s"
	@echo "... src/optix/ptx.o"
	@echo "... src/optix/ptx.i"
	@echo "... src/optix/ptx.s"
	@echo "... src/psdr.o"
	@echo "... src/psdr.i"
	@echo "... src/psdr.s"
	@echo "... src/scene/scene.o"
	@echo "... src/scene/scene.i"
	@echo "... src/scene/scene.s"
	@echo "... src/scene/scene_loader.o"
	@echo "... src/scene/scene_loader.i"
	@echo "... src/scene/scene_loader.s"
	@echo "... src/scene/scene_optix.o"
	@echo "... src/scene/scene_optix.i"
	@echo "... src/scene/scene_optix.s"
	@echo "... src/sensor/perspective.o"
	@echo "... src/sensor/perspective.i"
	@echo "... src/sensor/perspective.s"
	@echo "... src/sensor/sensor.o"
	@echo "... src/sensor/sensor.i"
	@echo "... src/sensor/sensor.s"
	@echo "... src/shape/mesh.o"
	@echo "... src/shape/mesh.i"
	@echo "... src/shape/mesh.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

